spring.application.name=workload-service
server.port=8082
# ===============================
# MONGODB
# ===============================
spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=${MONGODB_DATABASE}


# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
################
# JWT
################
secret.key=${SECRET_KEY}
################
# ACTIVEMQ
################
# ActiveMQ connection
spring.activemq.broker-url=${ACTIVEMQ_BROKER_URL}
spring.activemq.user=${ACTIVEMQ_USER}
spring.activemq.password=${ACTIVEMQ_PASSWORD}
# IMPORTANT: must match producer package
spring.activemq.packages.trust-all=true
# Connection pool (recommended ON for consumer)
spring.activemq.pool.enabled=true
spring.activemq.pool.max-connections=10
# JMS Listener (CORE for receiver)
spring.jms.listener.session.acknowledge-mode=auto
spring.jms.listener.auto-startup=true
spring.jms.listener.min-concurrency=5
spring.jms.listener.max-concurrency=10
# Queue mode (false = queue, true = topic)
spring.jms.pub-sub-domain=false
################
# Log Config
################
logging.level.root=info
# Console
logging.pattern.console=%date{dd MMM yyyy;HH:mm:ss.SSS}  %highlight(%-5level) %cyan(%logger{36}) - [%X{transactionId}] %green(%msg%n)
# File
logging.path.url=/epam_gym_microservice
logging.file.name=${logging.path.url}/app_log.log
logging.pattern.file=%date{dd MMM yyyy - HH:mm:ss.SSS} - %logger{36} - %-5level - [%X{transactionId}] %msg%n
logging.logback.rollingpolicy.max-file-size=500KB

################
# MANAGEMENT
################
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.shutdown.access=unrestricted
management.metrics.tags.application=gym-app
management.prometheus.metrics.export.enabled=true
management.info.env.enabled=true

################
# EUREKA
################

eureka.instance.preferIpAddress=true
eureka.client.fetchRegistry=true
eureka.client.registerWithEureka=true
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

################
# Info
################
info.app.name=${spring.application.name}
info.app.description=Main service for gym project
info.app.version=1.0