spring.application.name=workload-service
server.port=8082
# ===============================
# DATASOURCE
# ===============================
spring.datasource.url=jdbc:h2:mem:workloaddb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# H2 CONSOLE
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

################
# JWT
################
secret.key=${SECRET_KEY}
################
# ACTIVEMQ
################
# ActiveMQ connection
spring.activemq.broker-url=${ACTIVEMQ_BROKER_URL}
spring.activemq.user=${ACTIVEMQ_USER}
spring.activemq.password=${ACTIVEMQ_PASSWORD}

# IMPORTANT: must match producer package
spring.activemq.packages.trust-all=true

# Connection pool (recommended ON for consumer)
spring.activemq.pool.enabled=true
spring.activemq.pool.max-connections=10

# JMS Listener (CORE for receiver)
spring.jms.listener.session.acknowledge-mode=auto
spring.jms.listener.auto-startup=true
spring.jms.listener.min-concurrency=5
spring.jms.listener.max-concurrency=10

# Queue mode (false = queue, true = topic)
spring.jms.pub-sub-domain=false