services:
  eureka:
    image: sanjar1990/eureka:v1
    container_name: eureka-ms
    ports:
      - "8761:8761"
    networks:
      - gym
  main:
    image: sanjar1990/main:v1
    container_name: main-ms
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - gym
    environment:
      ACTIVEMQ_BROKER_URL: tcp://activemq-ms:61616
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-ms:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://main-db:5432/maindb
    depends_on:
      activemq:
        condition: service_started

      eureka:
        condition: service_started

      main-db:
        condition: service_healthy

  report:
    image: sanjar1990/report:v1
    container_name: report-ms
    ports:
      - "8082:8082"
    env_file:
      - .env
    networks:
      - gym
    environment:
      ACTIVEMQ_BROKER_URL: tcp://activemq-ms:61616
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-ms:8761/eureka
      MONGODB_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo-db:27017/reportdb?authSource=${MONGO_USERNAME}
      MONGODB_DATABASE: reportdb
    depends_on:
      activemq:
        condition: service_started

      eureka:
        condition: service_started
      mongo-db:
        condition: service_healthy


  activemq:
    image: webcenter/activemq:latest
    container_name: activemq-ms
    ports:
      - "61616:61616"   # JMS
      - "8161:8161"     # Web Console
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    networks:
      - gym
  main-db:
    image: postgres:13
    container_name: main-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: maindb
    networks:
      - gym
  mongo-db:
    image: mongo:7
    container_name: mongo-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: reportdb
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    healthcheck:
      test: >
        mongosh --username ${MONGO_USERNAME}
        --password ${MONGO_PASSWORD}
        --authenticationDatabase admin
        --eval "db.adminCommand('ping')"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - mongo-data:/data/db
    networks:
      - gym
networks:
  gym:
    driver: bridge
volumes:
  mongo-data: