### 14. Add Training (POST method)

POST localhost:8080/api/v1/training
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlcyI6WyJST0xFX1RSQUlORVIiLCJST0xFX0FETUlOIl0sInN1YiI6IkFubmEuS2hhbl90cmFpbmVyIiwiaWF0IjoxNzc5MDE0MjA0LCJleHAiOjE3NzkyNzM0MDR9.JmKoOSI52mXnbCAd5xByOW6sPNOTpZhZVjXKPqJk0wWYslFT0AUbCGyFYam8tUj7
Content-Type: application/json

{
  "traineeUsername": "TraineeTwo.MillerovTwo",
  "trainingDate": "2026-05-20",
  "trainingDuration": 50,
  "trainingTypeId": 3
}

### 12. Get Trainee Trainings List (GET method)

POST localhost:8080/api/v1/training/trainee
Content-Type: application/json

{
  "traineeUsername": "Ann.Miller",
  "trainerName": "Ali.Aliyev_trainer"
}

### 13. Get Trainer Trainings List (GET method)

POST localhost:8080/api/v1/training/trainer
Content-Type: application/json

{
  "trainerUsername": "Ali.Aliyev_trainer"
}

#### Delete Training (DELETE method)
DELETE localhost:8080/api/v1/training/229
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlcyI6WyJST0xFX1RSQUlORVIiLCJST0xFX0FETUlOIl0sInN1YiI6IkFubmEuS2hhbl90cmFpbmVyIiwiaWF0IjoxNzc5MDE0MjA0LCJleHAiOjE3NzkyNzM0MDR9.JmKoOSI52mXnbCAd5xByOW6sPNOTpZhZVjXKPqJk0wWYslFT0AUbCGyFYam8tUj7


