### GEt workload calculated by trainer username and date (GET method)
GET localhost:8082/api/v1/workload/Anna.Khan_trainer?year=2026&month=5
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlcyI6WyJST0xFX1RSQUlORVIiLCJST0xFX0FETUlOIl0sInN1YiI6IkFubmEuS2hhbl90cmFpbmVyIiwiaWF0IjoxNzc4NzU1MTYyLCJleHAiOjE3NzkwMTQzNjJ9.k3lFzQCYG6db_4eRMrLGO5F8PIGj6A11iHoA0Gp88PNT6hMtYHn6OB_xS0QtztnC
