################
# Spring Data Config
################
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true


################
# MANAGEMENT
################
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.shutdown.access=unrestricted
management.metrics.tags.application=gym-app
management.prometheus.metrics.export.enabled=true
management.info.env.enabled=true

################
# JWT
################
secret.key=${SECRET_KEY}
jwt.expiration.time=259200000


# ActiveMQ connection
spring.activemq.broker-url=${ACTIVEMQ_BROKER_URL}
spring.activemq.user=${ACTIVEMQ_USER}
spring.activemq.password=${ACTIVEMQ_PASSWORD}

# IMPORTANT: allow your DTO package
spring.activemq.packages.trust-all=true

# Disable pool (fine for dev; enable in prod)
spring.activemq.pool.enabled=true

# JMS Template settings (used by producer)
spring.jms.pub-sub-domain=false
spring.jms.template.delivery-mode=non_persistent
spring.jms.template.qos-enabled=true
spring.jms.template.time-to-live=36000
spring.jms.template.receive-timeout=1000
